import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/hero/Hero";
import Services from "@/components/services/Services";
import BrandAbout from "@/components/about/BrandAbout";
import SelectedBrands from "@/components/brands/SelectedBrands";
import Connect from "@/components/connect/Connect";
import Articles from "@/components/articles/Articles";
import Newslatter from "@/components/connect/Newslatter";
import Footer from "@/components/footer/Footer";
import { motion as m } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dev By Nate | Ivy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.75, ease: "easeInOut" }}
        className="px-4"
        // className=" absolute top-20 left-0 w-full h-full"
      >
        <Hero />
        <Services />
        <div className="h-[30vh]" />
        <BrandAbout />
        <SelectedBrands />
        <Connect />
        <Articles />
        <Newslatter />
      </m.main>
    </>
  );
}
