import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/hero/Hero";
import Services from "@/components/services/Services";
import BrandAbout from "@/components/about/BrandAbout";
import SelectedBrands from "@/components/brands/SelectedBrands";
import Connect from "@/components/connect/Connect";
import Articles from "@/components/articles/Articles";
import Newslatter from "@/components/connect/Newslatter";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" px-4">
        <Hero />
        <Services />
        <div className="h-[30vh]" />
        <BrandAbout />
        <SelectedBrands />
        <Connect />
        <Articles />
        <Newslatter />
      </main>
      <Footer />
    </>
  );
}
